"""
ARK (Autonomous Resilient Kernel) - Directory Initializer
==========================================================
Bootstraps the ARK project directory structure so that SYLPH agents
have a well-defined sanctuary to inhabit.
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path


# ---------------------------------------------------------------------------
# Directory skeleton definition
# ---------------------------------------------------------------------------

DIRECTORY_SKELETON: dict[str, str] = {
    # Core orchestrator
    "src/core": "Orchestrator core — manages the autonomous workflow loop.",
    # SYLPH agent logic & prompts
    "src/agents": "SYLPH agents — Architect, Coder, Reviewer prompts and logic.",
    # Memory / RAG back-ends
    "src/memory": "Memory layer — ChromaDB vector store and GraphRAG integration.",
    # Markdown specification documents
    "specs": "Design specifications written in Markdown (spec-driven development).",
    # AI-operated sandbox workspace
    "workspace": "Sandbox — AI-generated code is executed and verified here.",
}

# Package directories that also need an __init__.py
PYTHON_PACKAGES: tuple[str, ...] = (
    "src",
    "src/core",
    "src/agents",
    "src/memory",
)


def _write_readme(directory: Path, description: str) -> None:
    """Write a minimal README.md inside *directory*."""
    readme = directory / "README.md"
    if not readme.exists():
        readme.write_text(
            textwrap.dedent(f"""\
                # {directory.name}

                {description}
            """),
            encoding="utf-8",
        )


def _ensure_init(directory: Path) -> None:
    """Create an empty ``__init__.py`` if the directory is a Python package."""
    init = directory / "__init__.py"
    if not init.exists():
        init.write_text(
            '"""ARK package — auto-generated by initializer.py"""\n',
            encoding="utf-8",
        )


def initialize(root: Path | None = None) -> Path:
    """Create the ARK directory structure under *root*.

    Parameters
    ----------
    root:
        Project root directory.  Defaults to the directory that contains
        this script when ``None``.

    Returns
    -------
    Path
        The resolved project root that was initialised.
    """
    if root is None:
        root = Path(__file__).parent.resolve()
    else:
        root = Path(root).resolve()

    print(f"\n🚀  Initialising ARK skeleton under: {root}\n")

    created: list[str] = []
    skipped: list[str] = []

    for rel_path, description in DIRECTORY_SKELETON.items():
        directory = root / rel_path
        if directory.exists():
            skipped.append(rel_path)
        else:
            directory.mkdir(parents=True, exist_ok=True)
            created.append(rel_path)

        _write_readme(directory, description)

        if rel_path in PYTHON_PACKAGES:
            _ensure_init(directory)

    # ----- summary -----
    if created:
        print("  ✅  Created directories:")
        for d in created:
            print(f"       • {d}/")
    if skipped:
        print("  ⏭️   Already existed (skipped):")
        for d in skipped:
            print(f"       • {d}/")

    print(
        "\n🏛️  ARK directory structure is ready.\n"
        "    精霊（SYLPH）たちが宿る器の準備は万全です。\n"
    )
    return root


# ---------------------------------------------------------------------------
# CLI entry-point
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    """Entry-point for ``python initializer.py [root_dir]``."""
    if argv is None:
        argv = sys.argv[1:]

    root: Path | None = Path(argv[0]) if argv else None
    initialize(root)
    return 0


if __name__ == "__main__":
    sys.exit(main())
