"""
ARK — GitHub Publisher
=======================================================================
Orchestrator の最終フェーズで、GitHub へのプッシュや
Pull Request の作成を専門に担当するモジュール。
"""

import os
import logging
from typing import Optional
from src.core.dock import Dock

log = logging.getLogger("ARK.GitHubPublisher")

def publish_to_github(
    dock: Dock, 
    task_id: str, 
    goal: str, 
    is_new_project: bool, 
    is_url: bool
) -> Optional[str]:
    """
    リモートリポジトリの作成、ブランチの Push、PR の作成を実行する。
    成功した場合は、作成された Pull Request の URL を返す。

    Args:
        dock (Dock): 実行中のプロジェクトドック環境。
        task_id (str): タスクの一意識別子。
        goal (str): ユーザーが設定した最終目標。
        is_new_project (bool): 新規リポジトリ作成が必要かどうかのフラグ。
        is_url (bool): ターゲットが既にリモートURLであるか。

    Returns:
        Optional[str]: 成功時は PR の URL、失敗またはスキップ時は None。
    """
    # トークンや Git コンポーネントの存在を確認
    github_token = os.getenv("GITHUB_TOKEN")
    if not dock or not dock.git or not github_token:
        log.info("⚠️ [Publisher] GITHUB_TOKEN が未設定、または Git が未初期化のためスキップします。")
        return None

    try:
        # 1. 新規プロジェクトの場合は GitHub 上にリモートリポジトリを作成
        if is_new_project:
            log.info("🏗️ [Publisher] GitHub に新規リモートリポジトリを作成中...")
            # リポジトリ名の生成（ディレクトリ名を使用）
            repo_name = dock.path.name
            description = f"ARK Generated Project: {goal[:100]}..."
            
            repo_url = dock.git.create_remote_repo(
                name=repo_name,
                description=description
            )
            
            if repo_url:
                dock.git.setup_dock(repo_url)
                log.info("✅ [Publisher] リモートリポジトリとのリンクが完了しました。")
            else:
                log.warning("⚠️ [Publisher] リモートリポジトリの作成に失敗しました。ローカルのみで続行します。")
        elif not is_url:
            log.info("⚓️ [Publisher] 既存のリモートリポジトリ設定を確認しました。")

        # 2. 作業用トピックブランチを作成 (GitTool 内で task_id からブランチ名を生成)
        branch_name = dock.git.create_topic_branch(task_id)

        # 3. リモートが存在する場合、Push と PR 作成を実行
        # dock.git.push は成功時に True を返す想定
        log.info("[Publisher] ブランチ '%s' をリモートに Push 中...", branch_name)
        
        if dock.git.push(branch_name):
            # プルリクエストの情報を構築
            pr_title = f"ARK Update: {goal[:50]}..."
            pr_body = (
                f"## ARK Autonomous Update 🚢\n\n"
                f"**Mission Goal:**\n{goal}\n\n"
                f"**Task ID:** `{task_id}`\n\n"
                f"---\n"
                f"*Generated by ARK (Autonomous Resilient Kernel)*"
            )
            
            pr_url = dock.git.create_pull_request(
                branch_name=branch_name, 
                title=pr_title, 
                body=pr_body
            )
            
            if pr_url:
                log.info("🎉 [Publisher] Pull Request を作成しました: %s", pr_url)
                return pr_url
            else:
                log.warning("⚠️ [Publisher] PR の作成に失敗しました（既に存在するか権限エラーの可能性があります）。")
        else:
            log.warning("⚠️ [Publisher] Push に失敗したため、PR 作成を中止しました。")

    except Exception as e:
        log.error("❌ [Publisher] パブリッシュ処理中にエラーが発生しました: %s", e)

    return None