"""
ARK — Coder Agent (SYLPH)
==========================
実装フェーズを担当するエージェント。

責務
----
- :class:`~src.core.models.PlanPayload` を受け取りコードを生成し、
  :class:`~src.core.models.CodePayload` を返す。
- LLMレスポンスからファイルパスとコード本体を抽出する。
- パース失敗時はセーフなフォールバックコードを使用してループを継続する。
"""

from __future__ import annotations

import logging
import re
import textwrap
from typing import TYPE_CHECKING

from src.agents.base_agent import BaseAgent
from src.core.agents import build_coder_prompt
from src.core.models import CodePayload, FileAction, FileChange, PlanPayload

if TYPE_CHECKING:
    from src.core.providers import BaseProvider

log = logging.getLogger("ARK.Coder")

# ---------------------------------------------------------------------------
# System prompt
# ---------------------------------------------------------------------------

_SYSTEM_PROMPT = """\
あなたはARKフレームワークのCoder SYLPHです。
以下の実装計画に基づいてPythonコードを生成してください。

## 出力フォーマット（厳守）
FILE: <ファイルパス>
```python
<生成するコード全体>
```

## 制約
- Python 3.11+ に準拠すること
- すべての関数・メソッドに型ヒントを付けること
- モジュールに docstring を付けること

## 実装計画
ゴール: {goal}
対象ファイル: {target_files}
制約: {constraints}
受け入れ基準: {acceptance}

## 試行回数
{retry}回目の実装（0が初回）

{reviewer_feedback}
"""

_FEEDBACK_SECTION = """\
## 前回のレビュー結果（修正必須）
{feedback}
"""


# ---------------------------------------------------------------------------
# CoderAgent
# ---------------------------------------------------------------------------

class CoderAgent(BaseAgent):
    """実装担当SYLPHエージェント。

    LLMにPlanPayloadを渡してコードを生成し、 :class:`~src.core.models.CodePayload` を返す。

    Parameters
    ----------
    provider:
        使用する :class:`~src.core.providers.BaseProvider` 実装。
    """

    def __init__(self, provider: "BaseProvider", workspace_path: Path | None = None) -> None:
        super().__init__(provider, role="coder", workspace_path=workspace_path)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def code(
        self,
        plan: PlanPayload,
        retry: int,
        reviewer_feedback: str = "",
    ) -> CodePayload:
        """実装計画からコードを生成し :class:`~src.core.models.CodePayload` を返す。

        Parameters
        ----------
        plan:
            Architectが生成した :class:`~src.core.models.PlanPayload`。
        retry:
            現在の試行回数（0が初回）。
        reviewer_feedback:
            前回のレビューで指摘された内容（リトライ時に参照）。

        Returns
        -------
        CodePayload
            生成されたコードペイロード。LLMパース失敗時はフォールバックコードを使用。
        """
        log.info(
            "[Coder] Generating code (attempt %d) for: %s",
            retry + 1, plan.target_files,
        )

        # src/core/agents.py のロジックを使用してプロンプトを構築（初期コンテキスト取得を含む）
        prompt = build_coder_prompt(
            goal=plan.goal,
            target_files=plan.target_files,
            constraints=plan.constraints,
            acceptance=plan.acceptance_criteria,
            retry=retry,
            workspace_path=self._workspace_path,
            reviewer_feedback=reviewer_feedback
        )
        
        response = self._call_llm(prompt)
        return self._parse_response(response, plan=plan, retry=retry)

    # ------------------------------------------------------------------
    # Parser
    # ------------------------------------------------------------------

    def _parse_response(
        self,
        response: str,
        *,
        plan: PlanPayload,
        retry: int,
    ) -> CodePayload:
        """LLMレスポンスから :class:`~src.core.models.CodePayload` を抽出する。"""
        target_path = plan.target_files[0] if plan.target_files else "workspace/output.py"
        file_changes: list[FileChange] = []

        # FILE: <path> + ```python ... ``` ブロックを抽出
        pattern = r"FILE:\s*(.+?)\n```(?:python)?\n(.*?)```"
        matches = re.findall(pattern, response, re.DOTALL | re.IGNORECASE)

        for raw_path, code_body in matches:
            path = raw_path.strip()
            code = code_body.rstrip()
            if path and code:
                file_changes.append(
                    FileChange(path=path, action=FileAction.CREATE, content=code)
                )
                log.debug("[Coder] Parsed file: %s (%d bytes)", path, len(code))

        # パース失敗 → フォールバックコード
        if not file_changes:
            log.warning("[Coder] No valid code blocks found in LLM response — using fallback")
            file_changes = [self._fallback_file_change(target_path, plan.goal, retry)]

        return CodePayload(
            plan_ref=plan.goal[:40],
            files=file_changes,
            test_command=f"python {file_changes[0].path}",
            notes=f"Generated by CoderAgent (attempt {retry + 1})",
        )

    @staticmethod
    def _fallback_file_change(path: str, goal: str, retry: int) -> FileChange:
        """パース失敗時のフォールバック用 :class:`~src.core.models.FileChange` を生成する。"""
        content = textwrap.dedent(f"""\
            # ARK — Auto-generated by CoderAgent (fallback)
            # Goal: {goal}
            # Attempt: {retry + 1}
            \"\"\"ARK generated module.\"\"\"


            def main() -> None:
                \"\"\"Entry point.\"\"\"
                print("Hello from ARK CoderAgent!")


            if __name__ == "__main__":
                main()
        """)
        return FileChange(path=path, action=FileAction.CREATE, content=content)
